MUSIC_SHARING/Controllers/HomeController.cs
using MUSIC_SHARING.MUSIC_SHARING_BL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MUSIC_SHARING.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            HomeBL homeBL = new HomeBL();
            return View(homeBL.Initialize());
        }

        //public ActionResult GetSong(string songID)
        //{
        //    //var file = Server.MapPath("~/app_data/test.mp3");
        //    var file2 = @"D:\_MusicCenter\test.mp3";
        //    //System.Diagnostics.Debug.WriteLine(file);
        //    System.Diagnostics.Debug.WriteLine(file2);
        //    return File(file2, "audio/mp3");
        //}

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MUSIC_SHARING/Controllers/SongController.cs
using MUSIC_SHARING.MUSIC_SHARING.BL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MUSIC_SHARING.Controllers
{
    public class SongController : Controller
    {
        //
        // GET: /Song/
        public ActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public JsonResult UploadMusic(IEnumerable<HttpPostedFileBase> files)
        {
            SongBL songBL = new SongBL();
            bool result = songBL.InsertSong(files);
            string message = String.Empty;
            if (result)
            {
                message = "OK, ngon rồi";
            }
            else
            {
                message = "Đéo được, làm lại đi !";
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Test()
        {
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetSong(string songID)
        {
            SongBL songBL = new SongBL();

            string path = songBL.GetSongUrlByID(songID);

            return File(path, "audio/mp3");
        }


        [HttpPost]
        public ActionResult AddToDefaultList(string songID)
        {
            SongBL songBL = new SongBL();
            songBL.AddToDefaultList(songID);

            return Json("Ok man, add xong roi", JsonRequestBehavior.AllowGet);
        }

       
    }


}

MUSIC_SHARING/Views/Home/Index.cshtml
<div id="music-index" class="col-md-12 no-padding">
    @Html.Partial("~/Views/Music/_MusicIndex.cshtml")
</div>
<div id="music-upload" class="col-md-12">
    @Html.Partial("~/Views/Music/_MusicUpload.cshtml")
</div>
<div id="music-all-song" class="col-md-12">
    @Html.Partial("~/Views/Music/_MusicAllSong.cshtml")
</div>

<script>
    $(function () {

        //----- Tabs start -----

        $('#top-listen-fpt-tab').click(function () {
            if ($('#tabs-1').css('display') == 'block') {

            } else {
                hideAllTaps();
            }
            $('#tabs-1').fadeIn();
        });

        $('#top-listen-world-tab').click(function () {
            if ($('#tabs-2').css('display') == 'block') {

            } else {
                hideAllTaps();
            }

            $('#tabs-2').fadeIn();
        });
        $('#search-tab').click(function () {
            if ($('#tabs-3').css('display') == 'block') {

            } else {
                hideAllTaps();
            }

            $('#tabs-3').fadeIn();
        });

        function hideAllTaps() {
            $('#tabs-1').hide();
            $('#tabs-2').hide();
            $('#tabs-3').hide();
        }

        //----- Tabs end -----

        $('#music-index-tab').click(function () {
            if ($('#music-index').css('display') == 'block') {

            } else {
                fadeAll();
            }
            $('#music-index').delay('800').fadeIn();
        });

        $('#music-upload-tab').click(function () {
            if ($('#music-upload').css('display') == 'block') {

            } else {
                fadeAll();
            }
            $('#music-upload').delay('800').fadeIn();
        });

        $('#music-all-song-tab').click(function () {
            if ($('#music-all-song').css('display') == 'block') {

            } else {
                fadeAll();
            }
            $('#music-all-song').delay('800').fadeIn();
        });
    });

    function fadeAll() {
        $('#music-index').fadeOut();
        $('#music-upload').fadeOut();
        $('#music-all-song').fadeOut();
    }
</script>



MUSIC_SHARING/Views/Home/_SearchResult.cshtml


<h2>_SearchResult</h2>


MUSIC_SHARING/Views/Music/_MusicAllSong.cshtml


<h2>Music All Song</h2>

<script>
    $(function () {

    });
</script>

MUSIC_SHARING/Views/Music/_MusicIndex.cshtml
@using MUSIC_SHARING.MUSIC_SHARING.DTO;
@model MUSIC_SHARING.MUSIC_SHARING_DTO.HomeDTO
@{
    int countA = 1;
    int countB = 1;
}

<div class="col-md-6 border-right height-100-percent padding-top-10">
    <div id="now-play" class="row">

        <label>Song name + Artist</label>
        <audio id="music-play" controls>
            <source id="music-source" src="" type="audio/mpeg" />
        </audio>
        @*<button onclick="document.getElementById('demo').play()">Play the Audio</button>
            <button onclick="document.getElementById('demo').pause()">Pause the Audio</button>
            <button onclick="document.getElementById('demo').volume+=0.1">Increase Volume</button>
            <button onclick="document.getElementById('demo').volume-=0.1">Decrease Volume</button>*@
        <br />
        <label>Upload By :</label><br />
        <label>Upload Date :</label><br />
        <label>Number of listen :</label>
    </div>
    <hr />


    <div id="song-list" class="row">
        <label>Song list</label>

        @foreach (SongDTO song in Model.UserDefaultList)
        {
            <div class="col-md-12 no-padding inline-block song-item">
                <div class="col-md-1 no-padding text-center song-chart">
                    <span class="glyphicon glyphicon-tree-deciduous"></span>
                </div>

                <div class="col-md-9 no-padding">
                    <div class="col-md-12">
                        <div class="col-md-10 song-name no-padding">@song.SONG_NAME</div>
                        <div class="col-md-2 duration">@song.GetMinutes()</div>
                    </div>
                    <div class="col-md-12 artist"> @song.ARTIST</div>
                </div>

                <div class="col-md-2 no-padding text-center song-action">
                    <button title="Play this song" class="play-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-play"></span></button>&nbsp;&nbsp;
                    <button title="Remove from list" class="remove-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-remove"></span></button>
                </div>
            </div>
            <hr />
            countA++;
        }



        @*<div class="col-md-12 no-padding inline-block song-item">
            <div class="col-md-1 no-padding text-center song-chart">
                <span class="glyphicon glyphicon-tree-deciduous"></span>
            </div>

            <div class="col-md-9 no-padding">
                <div class="col-md-12">
                    <div class="col-md-10 song-name no-padding">I don't want to miss a thing</div>
                    <div class="col-md-2 duration">3:40</div>
                </div>
                <div class="col-md-12 artist"> artist</div>
            </div>

            <div class="col-md-2 no-padding text-center song-action">
                <button><span class="glyphicon glyphicon-play"></span></button>&nbsp;&nbsp;
                <button><span class="glyphicon glyphicon-remove"></span></button>
            </div>
        </div>*@

    </div>





</div>

<div class="col-md-6 height-100-percent padding-top-10">

    <div id="tabs" class="col-md-12 no-padding">
        <div id="tabs-nav" class="col-md-12 no-padding">
            <div class="col-md-4 taps-nav no-padding"><button id="top-listen-fpt-tab" class="tabs-button" type="button">Top Listen FPT</button></div>
            <div class="col-md-4 taps-nav no-padding"><button id="top-listen-world-tab" class="tabs-button" type="button">Top Listen World</button></div>
            <div class="col-md-4 taps-nav no-padding"><button id="search-tab" class="tabs-button" type="button">Search</button></div>
        </div>
        <div id="tabs-content" class="">
            <div id="tabs-1">
                @foreach (SongDTO song in Model.TopFPT)
                {
                    <div class="col-md-12 no-padding inline-block song-item">
                        <div class="col-md-1 no-padding text-center song-chart">
                            @countA
                        </div>

                        <div class="col-md-9 no-padding">
                            <div class="col-md-12">
                                <div class="col-md-10 song-name no-padding">@song.SONG_NAME</div>
                                <div class="col-md-2 duration">@song.GetMinutes()</div>
                            </div>
                            <div class="col-md-12 artist"> @song.ARTIST</div>
                        </div>

                        <div class="col-md-2 no-padding text-center song-action">
                            <button title="Play this song" class="play-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-play"></span></button>&nbsp;&nbsp;
                            <button title="Add to list" class="add-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-plus"></span></button>
                        </div>
                    </div>
                    <hr />
                    countA++;
                }
            </div>
            <div id="tabs-2">
                @foreach (SongDTO song in Model.TopWorld)
                {
                    <div class="col-md-12 no-padding inline-block song-item">
                        <div class="col-md-1 no-padding text-center song-chart">
                            @countB
                        </div>

                        <div class="col-md-9 no-padding">
                            <div class="col-md-12">
                                <div class="col-md-10 song-name no-padding">@song.SONG_NAME</div>
                                <div class="col-md-2 duration">@song.GetMinutes()</div>
                            </div>
                            <div class="col-md-12 artist"> @song.ARTIST</div>
                        </div>

                        <div class="col-md-2 no-padding text-center song-action">
                            <button title="Play this song" class="play-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-play"></span></button>&nbsp;&nbsp;
                            <button title="Add to list" class="add-button" data-songid="@song.SONG_ID"><span class="glyphicon glyphicon-plus"></span></button>
                        </div>
                    </div>
                    <hr />
                    countB++;
                }
            </div>
            <div id="tabs-3">
                <div class="col-md-12 no-padding inline-block song-item">
                    <p>Search</p>
                </div>
            </div>
            <hr />
            <div id="tags" class="col-md-12 no-padding">
                <label>Tags :</label><br />
                <p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p><p>xxx</p>
            </div>
        </div>
    </div>
</div>

<script>
    var musicPlay = document.getElementById("music-play");
    var addToListURL = '@Url.Action("AddToDefaultList", "Song")'
    $('.play-button').click(function () {

        var songID = $(this).data('songid');
        //alert(songID);
        var source = '@Url.Action("GetSong", "Song")?songID=' + songID;
        //alert(source);
        $('#music-source').attr("src", source).detach().appendTo(musicPlay);
        musicPlay.load();
        musicPlay.play();
    });

    $('.add-button').click(function () {

        var songID = $(this).data('songid');
        //alert(songID);
        $.ajax({
            url: addToListURL,
            type: "POST",
            dataType: "json", // data respone from server
            data: {songID:songID},

            // After request
            success: function (result) {
                alert(result)
            },
            error: function () {
                alert('fuck')
            }
        });


    });

    //mediaElement.seekable.start();  // Returns the starting time (in seconds)
    //mediaElement.seekable.end();    // Returns the ending time (in seconds)
    //mediaElement.currentTime = 20;
    //mediaElement.onseeked = function () {
    //    alert("Seek operation completed!");
    //};

    //mediaElement.addEventListener("seeked", function () {
    //    alert("Seek operation completed!");
    //});
</script>

MUSIC_SHARING/Views/Music/_MusicUpload.cshtml

<link href="~/Content/music.css" rel="stylesheet" />

<h2>Music upload</h2>

<div class="col-lg-12">
    <div class="col-lg-4">

        @* Basic Form *@
        @*<form method="post" action="@Url.Action("UploadMusic","Song")" enctype="multipart/form-data">
                <input type="file" name="files" multiple />
                <input type="submit" id="submit" value="Upload" />
            </form>*@


        @* Ajax Form *@
        <form id="upload-form" method="post" enctype="multipart/form-data">
            <input type="file" id="files" name="files" multiple accept="audio/*" />
        </form>
        <br />
        <button type="button" id="submit" disabled>Fuck</button>

    </div>
    <div class="col-lg-8">
        <div id="progress"></div>
    </div>
</div>
<div class="col-lg-12" style="margin-top:100px">

    <div id="file-choise"></div>
</div>
<script>

    var uploadURL = "@Url.Action("UploadMusic","Song")";

    $(function () {

        // Check if file not select
        $('#files').change(function () {
            var fileArray = $('#files').val();
            if (fileArray != '') {
                $('#submit').removeAttr('disabled');

                // Get file array
                var formInput = document.querySelector("#files");
                var files = formInput.files;
                //alert(files.length);

                var count = 1;
                $('#file-choise').text('');
                for (var i = 0; i < files.length; i++) {

                    $('#file-choise').append('<p>' + count + '. ' + files[i].name + '</p>');
                    count++;
                }
            } else {
                $('#file-choise').text('');
                $('#submit').prop('disabled', true);
            }
        });

        $('#submit').click(function () {

            // Get form data
            var formData = new FormData($('form')[0]);

            $.ajax({
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();

                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = evt.loaded / evt.total;
                            percentComplete = parseInt(percentComplete * 100);

                            // Do something with progress here
                            $('#progress').text('Uploading : ' + percentComplete + ' %');
                            //console.log(percentComplete);

                            if (percentComplete === 100) {

                            }

                        }
                    }, false);

                    return xhr;
                },

                url: uploadURL,
                type: "POST",
                dataType: "json", // data respone from server
                data: formData,

                //Options to tell jQuery not to process data or worry about content-type.
                cache: false,
                contentType: false,
                processData: false,

                // After request
                success: function (result) {
                    alert(result)
                },
                error: function () {
                    alert('fuck')
                }
            });
        });
    });
</script>

MUSIC_SHARING/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fuck you !</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">I Must Go</a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="navbar-form navbar-left">
                    <input type="text" placeholder="Search any thing !" class="form-control">
                    <span class="glyphicon glyphicon-search search-icon"></span>
                </div>
                <div class="tab-section navbar-left">
                    <ul class="nav navbar-nav">
                        <li><a id="music-index-tab" href="#music">Music</a></li>
                        <li><a id="music-all-song-tab"  href="#all-song">All Song</a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li id="music-upload-tab"><a href="#upload-music">Upload Music</a></li>
                    <li><a href="#music">Notification</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="main-section">
        <!-- Left menu -->
        <div class="left-col">
            @Html.Partial("~/Views/Shared/_LeftCol.cshtml")
        </div>
        <!-- Center -->
        <div class="container body-content right-col">
            @RenderBody()
        </div>
    </div>

   
</body>
</html>

MUSIC_SHARING/Views/Shared/_LeftCol.cshtml
<div id="logo" class="col-lg-12">
    <img id="logo-image" src="../Image/logo.jpg" />
</div>
<div id="slogan" class="col-lg-12">
    <span id="some-text">Listen music to much is wasting time !</span>
</div>
<br />
<br />
<nav id="main-nav">
    <ul class="main-navigation">
        <li><a href="/about/">about</a></li>
        <li><a href="/archive">archives</a></li>
        <li><a href="https://github.com/Haacked/feedback/issues/new">contact</a></li>
        <li><a href="/contributors">contributors</a></li>
    </ul>
</nav>
